dist: trusty

language: node_js

node_js:
  - "6"
  - "7"

install:
  - "npm install nodegit@0.18"
  - "npm install"

script:
  - "npm test"

after_success:
  - "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"

env:
  - CXX=g++-4.9

addons:

  apt:

    sources:
      - ubuntu-toolchain-r-test
      - git-core

    packages:
      - g++-4.9
      - git
